# Generated by Django 2.2 on 2022-02-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='venue',
            field=models.CharField(default="Sammy's", max_length=255),
            preserve_default=False,
        ),
    ]
