# Generated by Django 2.2 on 2022-02-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220212_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='user_rsvps', to='main_app.User'),
        ),
    ]
