# Generated by Django 2.2 on 2022-02-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220212_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='date',
            new_name='show_date',
        ),
    ]
